### ISSUE TITLE
You can unload logs that are under other logs in the logspace

### ISSUE THREAD

**Issue by gaviarctica** [gaviarctica/forestry-game-frontend#19]
Way to reproduce the bug:
1. Go to the striproad map (straight one with 4 unloading stations)
2. Drive down and pick up all the brown and yellow logs on the way
3. In the end unload 3 yellow logs to the right deposit and 2 brown logs to the left leaving 2 brown logs to the logspace
4. Pick up the orange log behind you
5. You can still unload the brown logs that are under the orange log in your logspace

**Comment by kavaari** [comment]
should be fixed now

**Comment by nime88** [comment]
Closing issue since this can't be reproduced anymore
