### ISSUE TITLE
Quit button in game screen causes weird error

### ISSUE THREAD

**Issue by nime88** [gaviarctica/forestry-game-frontend#27]
When pressing the quit button in game screen following console log error will appear.

proxyConsole.js:54 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Game component.

**Comment by gaviarctica** [comment]
I was wondering about that too earlier and now realized that the time counter only resets when you clear a level, not when you click quit so it stays running. Fixed in commit aaae8c5.
