### ISSUE TITLE
Error when trying to draw a road in editor

### ISSUE THREAD

**Issue by gaviarctica** [gaviarctica/forestry-game-frontend#28]
TypeError: Cannot read property 'length' of undefined

Has something to do with anomalies:
```
  42 |    };
  43 | 
  44 |    // parsing through the anomalies if there are any in the nodes
> 45 |    if(startNode.anomalies.length > 0 || endNode.anomalies.length > 0) {
  46 |      this.anomalies = [];
  47 | 
  48 |      for(var i = 0; i < startNode.anomalies.length; ++i) {
```

**Comment by nime88** [comment]
Should be fixed now (probably some undefined variable was used in editors end when creating nodes thus crashing the null check on node). Was fixed by adding undefined check, however null or empty array is still recommended.

**Comment by gaviarctica** [comment]
Yep, working now. It was still crashing when adding a deposit (unrelated reason) which I just fixed as well.
