### ISSUE TITLE
One way routes weird behaviour

### ISSUE THREAD

**Issue by gaviarctica** [gaviarctica/forestry-game-frontend#30]
I found a few (probably related) bugs with the one way roads:

- You can't reverse into the arrow's direction in Keskisormen Suo (like you should be able to, right, since it's supposed to be a slope or something?)
- In some cases you can't drive forwards into the arrow's direction (example follows)
- In some cases you can reverse into the opposite direction of the arrow's direction (example follows)

### Example
Use this image for reference: https://imgur.com/aHc58QW

Image arrows explained:
- Yellow: you **can** drive forwards in this direction, as you should be able to
- Blue: you **can** reverse in this direction (you should only be able to do that in the middle case)
- Red: you **can not** drive forwards in this direction, like you should be able to
- Purple: you **can not** reverse in this direction, like you should be able to

Mapdata for the example scenario:
```
{
"startpoint" : {"x": 0, "y": 0},
"routes": [
  {"x": 0, "y": 0, "route_node": 1, "to": [2]},
  {"x": 0, "y": 500, "route_node": 2, "to": [3]},
  {"x": 400, "y": 500, "route_node": 3, "to": [4], "anomalies": [{ "to" : 2, "one_way_road" : true}]},
  {"x": 800, "y": 300, "route_node": 4, "to": []},
  {"x": 400, "y": 800, "route_node": 5, "to": [3], "anomalies": [{ "to" : 3, "one_way_road" : true}]},
  {"x": -300, "y": 1000, "route_node": 6, "to": [5], "anomalies": [{ "to" : 5, "dying_road" : 20}]},
  {"x": -700, "y": 400, "route_node": 7, "to": [6,2], "anomalies":[{"to": 8, "one_way_road": true}]},
  {"x": -700, "y": 0, "route_node": 8, "to": [7,1]}
],
"logs": [
   {"x": 100, "y": 450, "type": 0},
   {"x": 200, "y": 450, "type": 1},
   {"x": 300, "y": 450, "type": 2},
   {"x": 400, "y": 450, "type": 3},
   {"x": -100, "y": 440, "type": 0},
   {"x": -200, "y": 420, "type": 1},
   {"x": -300, "y": 400, "type": 2},
   {"x": -400, "y": 380, "type": 3},
   {"x": -200, "y": -50, "type": 4},
   {"x": -100, "y": -50, "type": 5},
   {"x": -200, "y": -50, "type": 4},
   {"x": -300, "y": -50, "type": 5},
   {"x": -400, "y": -50, "type": 4},
   {"x": -500, "y": -50, "type": 5},
   {"x": -600, "y": -50, "type": 4},
   {"x": -700, "y": -50, "type": 5},
   {"x": 460, "y": 550, "type": 1},
   {"x": 460, "y": 570, "type": 3},
   {"x": 600, "y": 330, "type": 1},
   {"x": 540, "y": 360, "type": 3},
   {"x": 480, "y": 390, "type": 5}
],
"logdeposits" : [
   {"x": 700, "y": 240},
   {"x": 700, "y": 445}
]
}
```

Maybe this has something to do with the road segments being straight or almost straight. I tried moving a few of the nodes a little bit and it started to work similarly to how it works in Keskisormen Suo. But for example changing node 2's y-coordinate to 510 wasn't enough to correct the behaviour. When changed to 440 it did allow driving forwards into the arrow's direction though.

I believe the function **canDriveTo()** in _routesegment.js_ and specifically the math thing in there holds the answer for these bugs, but am not sure.

**Comment by nime88** [comment]
Now, one way roads should work **consistently**. So that one can only drive normally to the arrows direction (forward or reverse). Tested on example scenario above and on "Keskisormen suo" map.

**Comment by gaviarctica** [comment]
Tested and confirmed working.
