### ISSUE TITLE
You can set a null amount of dying road or weight limit value to another anomaly in editor

### ISSUE THREAD

**Issue by gaviarctica** [gaviarctica/forestry-game-frontend#37]
eg.
1. Go to editor
2. Create a level with a weight limited route segment
3. Choose dying road tool
3. Hover over weight limited route and press any number key(s)
4. Save level
5. Play level and see that you cant drive the segment even if you are under the set weight limit

Doing this makes the mapdata have a route like this:
`{"route_node":2,"x":96,"y":-299.5,"to":[1,3],"anomalies":[{"to":3,"weight_limit":1,"dying_road":null}]}`

If you do it the other way around the graphics change too and you will see the "fake" weight limited road say '_NaNkg_' in editor and '_nullkg_' in game.

One way road gets the null values added and is affected by 
`"dying_road":null` as well.

**Comment by nime88** [comment]
This particular instance should be fixed now. There might be some other random possibility to create multiple anomalies to same segment as it is only modifying the anomaly arrays in nodes.

**Comment by gaviarctica** [comment]
Yep, working
