### ISSUE TITLE
Route node index bug in forest.js

### ISSUE THREAD

**Issue by Torbe10** [gaviarctica/forestry-game-frontend#51]
line 42
var end = {x:this.mapdata.routes[this.mapdata.routes[i].to[j]].x,y:this.mapdata.routes[this.mapdata.routes[i].to[j]].y};

Crashes with old maps with indexes 1 to N. New maps are indexed from 0 to N-1 and works fine with those.

**Comment by nime88** [comment]
Updated default maps in init_data to index 0 to N-1, thus commited this fix.
