### ISSUE TITLE
Routes connected to the first node in editor are not getting linked

### ISSUE THREAD

**Issue by gaviarctica** [gaviarctica/forestry-game-frontend#54]
1. Editor
2. Draw any route
3. Draw another route starting from the first node of the first route
4. Play the map
5. You can't drive from the first drawn route to the second or vice versa

So the _'to'_ array of the first node won't have a connection to the new node like it should.

**Comment by gaviarctica** [comment]
It works if you start the second segment from empty space and then connect to the first node but not when starting from the first node.

**Comment by kavaari** [comment]
fixed

**Comment by kavaari** [comment]
pls test

**Comment by gaviarctica** [comment]
Tested and working 5/5
