### ISSUE TITLE
Renderer

### ISSUE THREAD

**Issue by Torbe10** [gaviarctica/forestry-game-frontend#6]
If hardware accel is disabled in browser or WebGL is not supported, PIXI uses CanvasRenderer and some graphics won't work the same way as with WebGL.

**Comment by nime88** [comment]
Probably need some concrete example of this one. Only thing I found was resolution of objects, which really do not matter. And there seem to be some bugs in PIXI it self (https://github.com/pixijs/pixi.js/issues/4317).

**Comment by gaviarctica** [comment]
One example is the use of tint on the log unloading stations when you get near them. The tint effect is not visible when using CanvasRenderer.
