### ISSUE TITLE
SVG not updated if map is updated

### ISSUE THREAD

**Issue by kavaari** [gaviarctica/forestry-game-frontend#74]

**Comment by kavaari** [comment]
caching?

**Comment by gaviarctica** [comment]
It does update on Chrome but not sure about other browsers.
I had to add
`response['Cache-control'] = 'max-age=0, must-revalidate, no-store'`
in python to make it work on chrome, might need something more for other browsers then :\

**Comment by gaviarctica** [comment]
Yeah, not updating on Firefox apparently
